"""IPdfSourceRepository — async Protocol for the PdfSource aggregate."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .entity import PdfSource


class IPdfSourceRepository(Protocol):
    async def save(self, source: PdfSource) -> PdfSource: ...
    async def get_by_id(self, source_id: UUID) -> PdfSource | None: ...
    async def list_all(self) -> list[PdfSource]: ...
    async def update(self, source: PdfSource) -> PdfSource: ...
    async def delete(self, source_id: UUID) -> None: ...
    async def count_pending(self) -> int: ...
