"""Interface de repositório para rounds (Protocol — duck typing)."""
from __future__ import annotations

from typing import Optional, Protocol
from uuid import UUID

from domain.round.entity import Round, RoundAction


class IRoundRepository(Protocol):
    async def save(self, round_: Round) -> Round: ...
    async def get_by_id(self, round_id: UUID) -> Optional[Round]: ...
    async def get_active_by_session(self, session_id: UUID) -> Optional[Round]: ...
    async def get_last_round_number(self, session_id: UUID) -> int: ...
    async def save_action(self, action: RoundAction) -> None: ...
    async def update_action(self, action: RoundAction) -> None: ...
